apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
stringData:
    token: ENC[AES256_GCM,data:WuecHX4yi2siMdWPMBiTeMo7bccLAA57JielhDhGywQhTcWf8Py0l32OXCX9bKsVjycjvbixZIfwTuFuF02IwQ1DMjeZPklqAIq4dnfYGd1+XGNXK1jjoW8vZiL4Nw==,iv:a/eEadafpF7RrdUxxlQL748RBUWAiYl/ltC3psaERqc=,tag:AIAniePnp6qenk1Zh4AOaQ==,type:str]
    ORG_ID: ENC[AES256_GCM,data:AafoiTNlEhkr9WcesvHrbaXja48o8tBRu3FOUJmI6Xr4+rbC,iv:Yi9o1enSGOc7kyE778FaBiXMLKz3vcz7Q403xHUhbDE=,tag:3NlcYNTzYN7SFxp1Zx9bSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZblNOZUJvdEg3SjhjVlhl
            VllIZFN4amRyQ2J6a3JyaVA1RE13Snp1MEVjCjJhN1NWajB5R00xSy9GWXZ6THVH
            b2NtTExIckM1SklLSWVGNGZEZ2NpOEUKLS0tIGlyajdIWWpLTWpVYWVpRk1PU3hL
            S2M5Q2pPZExkcmt2RFcrcllRa0xQYlUKAK3HPgYLcSLk9RQqqiE3JLFLyOl6O94V
            sOS9qTD6OXmqeLBD5lfM7Wsq29qP9RyR6YW+PjUdAcbSDTn8zc03tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-19T14:26:12Z"
    mac: ENC[AES256_GCM,data:9CZsbdQAcgU2VDLMSQfEBS8Rmy5jKjOqpZBFy7H5+/1Es5zLvEP8uyYj94oujWsSTJieYG/yR3pDtir1nY6JXWuUaAMLEZGE1E8IwL82vVxjEXg9MHZuJ166x8WjFkiccDU87Hs5NFSjsA4NmZdxlPRPEfFZiHlfM03uphX93Io=,iv:AxOVhRYrYP/JuaIhpzNlFPQupZv6s26kCQXAqn0dH5I=,tag:T3+mYN0muXrw7Td0suE85g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
