---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        objstore.yml: |-
          config:
            access_key: {{ .access_key }}
            bucket: thanos
            endpoint: {{ .endpoint }}
            insecure: false
            region: ca-west-1
            secret_key: {{ .secret_key }}
          type: s3
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3b394062-b12c-441f-97e3-b1090171d442
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3b394062-b12c-441f-97e3-b1090171d442
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b5f81ba-ccbe-4e28-add2-b1070041df95
        property: endpoint
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  target:
    name: alertmanager-secret
    deletionPolicy: Delete
    template:
      templateFrom:
        - configMap:
            name: alertmanager-config-tpl
            items:
              - key: alertmanager.yaml
  refreshInterval: 5m
  data:
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 46dcebd0-438f-4b5d-99ae-b1300108cafe
        property: alertmanager_pushover_token
    - secretKey: PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 5fdae434-01f1-4c88-bb83-b1300103c1d7
        property: pushover_user_key
