---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name kube-prometheus-stack
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        objstore.yml: |-
          config:
            access_key: {{ .access_key }}
            bucket: thanos
            endpoint: {{ .endpoint }}
            insecure: false
            region: ca-west-1
            secret_key: {{ .secret_key }}
          type: s3
  dataFrom:
  - extract:
      key: minio
  - extract:
      key: prometheus
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name alertmanager
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: alertmanager-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: alertmanager-config-tpl
            items:
              - key: alertmanager.yaml
  dataFrom:
  - extract:
      key: alertmanager
  - extract:
      key: pushover
