---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        objstore.yml: |-
          config:
            access_key: {{ .access_key }}
            bucket: thanos
            endpoint: {{ .endpoint }}
            insecure: false
            region: ca-west-1
            secret_key: {{ .secret_key }}
          type: s3
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3b394062-b12c-441f-97e3-b1090171d442
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3b394062-b12c-441f-97e3-b1090171d442
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b5f81ba-ccbe-4e28-add2-b1070041df95
        property: endpoint
