---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./prometheusrules
configMapGenerator:
  - name: kube-state-metrics-configmap
    files:
      - kube-state-metrics.yaml=./resources/kube-state-metrics.yaml
  - name: alertmanager-config-tpl
    files:
      - alertmanager.yaml=./resources/alertmanager.yaml
generatorOptions:
  disableNameSuffixHash: true
