apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0LQQzUB9zF7DxjmrHrXMmRGk91UbJ0Ay38suZLUib1mD969OFXSPIQ==,iv:vvouI84Y3XXiAhpgCmzwPM+12pUcaoQH+C/OEW/197M=,tag:TbRXN0uSYxKmfgIg+rrorA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb0diNGVjdmN2UXE0NU5h
            emdOUi93bTBlQjZoYWZaUWpJV0doYVBIQWg4CjNXNmRLaEgxR25KNVM1ejFxQU0z
            SERYSXNsNmFYcVVMQm04SWFnbW1tTjAKLS0tIDhESmZ6QVpSMzhrdWJEcTN6R1o5
            VDFGcnM5OXRMTGMwZEdwMTZxU0NKSzgKE3b4nlRreh2wa9r/VpaavRL6akQZKuI7
            pU8sPBk8SP0Oe1g7W/LFZA+8QPtxJY/Lw5iKouRknSzag+cMtawpvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T22:01:04Z"
    mac: ENC[AES256_GCM,data:tkVKecqPC3EHkYZthTgM4YvEthd8/Np/a49bGhxJrb6oJutkoN9ZcREFUPtYgRo+1jxPpuRMCVAHLCGFrUtxdD/yBYwUM1Valo5lEThCt0qV6lxXDPgHOA9XKpxjUUQiliPEPSDHGh9vNXrDBZ72h9g1daw5X5oScaq37x1q22o=,iv:XK8xJw/uhvFMKQSgXUnKmAWiXJNS0Q6UzL5IAwGYSKE=,tag:f0nanw91cWuNdnc9LiwYaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
