---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bitwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/joryirving/bitwarden-cli
              tag: 2024.2.1@sha256:74c00a7ac5d35ca4a86f8f00fc9abe1f3cdec59239a48bed8f2b9f04004a468b
            envFrom:
              - secretRef:
                  name: bitwarden-cli
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:  ["wget", "-q", "http://127.0.0.1:8087/sync", "--post-data=''"]
                  timeoutSeconds: 5
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      main:
        ports:
          http:
            port: 8087
