---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik-charts.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./csi-driver-smb.yaml
  - ./democratic-csi.yaml
  - ./descheduler.yaml
  - ./dragonfly-charts.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds-charts.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./node-feature-discovery.yaml
  - ./metrics-server.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./xenitab.yaml
