---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app tdarr-node
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: deployment
        containers:
          main:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node_acc
              tag: 2.17.01
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              serverIP: 10.10.5.40
              serverPort: 8266
              PUID: 568
              PGID: 568
              ffmpegPath: "/usr/local/bin/ffmpeg"
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: intel.feature.node.kubernetes.io/gpu
                  operator: In
                  values:
                    - "true"
    service:
      main:
        enabled: false
        ports:
          enabled: false
          http:
            port: 8265

    persistence:
      media:
        enabled: true
        type: hostPath
        hostPath: ${SECRET_MFS_DATA:=temp}
        globalMounts:
          - path: /mnt/moosefs
