---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        PI_DOMAIN: "{{ .PI_DOMAIN }}"
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 77e30fff-fad7-4812-a635-b034002b5b17
        property: discord_webhook
    - secretKey: POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 77e30fff-fad7-4812-a635-b034002b5b17
        property: pg_user
    - secretKey: POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 77e30fff-fad7-4812-a635-b034002b5b17
        property: pg_password
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 7a5661cb-9655-422b-8506-b02900fbc4e1
        property: password
    - secretKey: PI_DOMAIN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 136c1200-904a-4e3c-bd02-ac6e00f706e3
        property: pi_domain
