---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        s3-bucket: thanos
        s3-region: us-east-1
        s3-endpoint: "{{ .endpoint }}"
        access-key: "{{ .access_key }}"
        secret-key: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 517f9c15-6822-45e7-9a60-b10a00e92386
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 517f9c15-6822-45e7-9a60-b10a00e92386
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b5f81ba-ccbe-4e28-add2-b1070041df95
        property: endpoint
