---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name thanos-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      data:
        s3-bucket: &bucket thanos
        s3-endpoint: &endpoint "{{ .endpoint }}"
        access-key: &access_key "{{ .access_key }}"
        secret-key: &secret_key "{{ .secret_key }}"
        BUCKET_NAME: *bucket
        BUCKET_HOST: *endpoint
        BUCKET_REGION: ""
        AWS_ACCESS_KEY_ID: *access_key
        AWS_SECRET_ACCESS_KEY: *secret_key
  dataFrom:
  - extract:
      key: thanos
  - extract:
      key: minio
