---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        s3-bucket: thanos
        s3-region: ca-west-1
        s3-endpoint: "{{ .endpoint }}"
        access-key: "{{ .access_key }}"
        secret-key: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 69af7022-f28c-4152-90a7-b0560025eaa7
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 69af7022-f28c-4152-90a7-b0560025eaa7
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5a98804c-6c54-4e09-817e-afd8012c70ad
        property: endpoint
