---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        s3-bucket: &bucket thanos
        s3-endpoint: &endpoint "{{ .endpoint }}"
        access-key: &access_key "{{ .access_key }}"
        secret-key: &secret_key "{{ .secret_key }}"
        BUCKET_NAME: *bucket
        BUCKET_HOST: *endpoint
        BUCKET_REGION: ""
        AWS_ACCESS_KEY_ID: *access_key
        AWS_SECRET_ACCESS_KEY: *secret_key
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 517f9c15-6822-45e7-9a60-b10a00e92386
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 517f9c15-6822-45e7-9a60-b10a00e92386
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8b5f81ba-ccbe-4e28-add2-b1070041df95
        property: endpoint
