---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thanos
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: thanos
      version: 12.23.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.34.0
    objstoreConfig:
      type: s3
      config:
        insecure: true
    queryFrontend:
      enabled: true
      replicaCount: 2
      ingress:
        enabled: true
        ingressClassName: internal
        hostname: &host thanos-query-frontend.${SECRET_DOMAIN}
        tls: true
        extraTls:
          - hosts:
              - *host
    query:
      enabled: true
      replicaCount: 2
      replicaLabel: ["__replica__"]
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: observability
      stores: ["thanos-svc.${SECRET_DOMAIN}:10901"]
    bucketweb:
      enabled: true
      replicaCount: 2
    compactor:
      enabled: true
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 14d
      retentionResolution5m: 30d
      retentionResolution1h: 60d
      persistence:
        enabled: true
        storageClass: moosefs-storage
        size: 10Gi
    storegateway:
      enabled: true
      replicaCount: 2
      persistence:
        enabled: true
        storageClass: moosefs-storage
        size: 10Gi
    ruler:
      enabled: true
      replicaCount: 2
      replicaLabel: __replica__
      alertmanagers: ["http://alertmanager.observability.svc.cluster.local:9093"]
      extraFlags: ["--web.prefix-header=X-Forwarded-Prefix"]
      config: |-
        groups:
          - name: PrometheusWatcher
            rules:
              - alert: PrometheusDown
                annotations:
                  summary: A Prometheus has disappeared from Prometheus target discovery
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
                for: 5m
                labels:
                  severity: critical
      persistence:
        enabled: true
        storageClass: moosefs-storage
        size: 10Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
