---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        WHISPARR__API_KEY: &apiKey "{{ .WHISPARR__API_KEY }}"
        WHISPARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        WHISPARR__POSTGRES_PORT: "5432"
        WHISPARR__POSTGRES_USER: &dbUser "{{ .WHISPARR__POSTGRES_USER }}"
        WHISPARR__POSTGRES_PASSWORD: &dbPass "{{ .WHISPARR__POSTGRES_PASSWORD }}"
        WHISPARR__POSTGRES_MAIN_DB: whisparr_main
        WHISPARR__POSTGRES_LOG_DB: whisparr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: whisparr_main whisparr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: WHISPARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: eddfd7e2-0540-4eae-8d85-b12f01060c56
        property: token
    - secretKey: WHISPARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: eddfd7e2-0540-4eae-8d85-b12f01060c56
        property: pg_user
    - secretKey: WHISPARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: eddfd7e2-0540-4eae-8d85-b12f01060c56
        property: pg_password
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6c1e4615-5100-4dab-a169-b107003f2677
        property: password
