---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name whisparr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        WHISPARR__API_KEY: &apiKey "{{ .whisparr_token }}"
        WHISPARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        WHISPARR__POSTGRES_PORT: "5432"
        WHISPARR__POSTGRES_USER: &dbUser "{{ .pg_user }}"
        WHISPARR__POSTGRES_PASSWORD: &dbPass "{{ .pg_pass }}"
        WHISPARR__POSTGRES_MAIN_DB: whisparr_main
        WHISPARR__POSTGRES_LOG_DB: whisparr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: whisparr_main whisparr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
  dataFrom:
  - extract:
      key: whisparr
  - extract:
      key: cloudnative-pg
