---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name grafana-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
        # Admin User
        adminUser: "{{ .adminUser }}"
        adminPass: "{{ .adminPass }}"
        # App
        GF_DATABASE_USER: &dbUser "{{ .pg_user }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .pg_pass }}"
        GF_DATABASE_HOST: &dbHost postgres-rw.database.svc.cluster.local
        GF_DATABASE_NAME: &dbname grafana
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
        # Datasources
        TESLAMATE_POSTGRES_PASSWORD: "{{ .teslamate_pg_pass }}"
  dataFrom:
  - extract:
      key: grafana
  - extract:
      key: teslamate
  - extract:
      key: cloudnative-pg

