---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Authentik
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
        # Admin User
        adminUser: "{{ .adminUser }}"
        adminPass: "{{ .adminPass }}"
        # App
        GF_DATABASE_USER: &dbUser "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_HOST: &dbHost postgres-rw.database.svc.cluster.local
        GF_DATABASE_NAME: &dbname grafana
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: client_id
    - secretKey: client_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: client_secret
    - secretKey: adminUser
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: username
    - secretKey: adminPass
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: password
    - secretKey: GF_DATABASE_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: pg_user
    - secretKey: GF_DATABASE_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b36a66be-7898-4003-902a-afc701166ed9
        property: pg_password
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6c1e4615-5100-4dab-a169-b107003f2677
        property: password
