---
apiVersion: v1
kind: ConfigMap
metadata:
  name: themepark-gatus-ep
  namespace: services
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: theme-park
        group: services
        url: https://theme-park.${SECRET_DOMAIN}.com/
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
