---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gatus-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .pg_user }}"
        INIT_POSTGRES_PASS: "{{ .pg_pass }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
  dataFrom:
  - extract:
      key: gatus
  - extract:
      key: cloudnative-pg
