image:
  repository: ghcr.io/ajnart/homarr
  tag: "0.14.4"
  pullPolicy: IfNotPresent 

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

env:
  TZ: UTC

service:
  main:
    ports:
      http:
        port: 7575

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: homarr.hamcloud.io
        paths:
          - path: /
    tls:
      - secretName: homarr-tls
        hosts:
          - homarr.hamcloud.io

persistence:
  configs:
    enabled: true
    mountPath: /app/data/configs
    retain: true
    accessMode: ReadWriteMany
    size: 10Gi
  data:
    enabled: true
    mountPath: /data
    retain: true
    accessMode: ReadWriteMany
    size: 10Gi
  icons:
    enabled: true
    mountPath: /app/public/icons
    retain: true
    accessMode: ReadWriteMany
    size: 10Gi
nodeSelector:
  location: local

