---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-image-cleanup-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  data:
    - secretKey: PLEX_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 557de7c6-1ee4-4ef5-9eaa-b10900f5c0ff
        property: token
