---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "moosefs-csi"
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        master_host: "{{ .MOOSEFS_MASTER_HOST }}"
        master_port: "{{ .MOOSEFS_MASTER_PORT }}"
        k8s_root_dir: "/"
        driver_working_dir: "pv_data"
        mount_count: "1"
        mfs_logging: "true"
  data:
    - secretKey: MOOSEFS_MASTER_HOST
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9d963301-43d3-4c08-b532-1434c3afdc35
        property: mfshost
    - secretKey: MOOSEFS_MASTER_PORT
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 9d963301-43d3-4c08-b532-1434c3afdc35
        property: mfsport
