---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name csi-moosefs-config
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        master_host: "{{ .host }}"
        master_port: "{{ .port }}"
        k8s_root_dir: "/"
        driver_working_dir: "pv_data"
        mount_count: "1"
        mfs_logging: "true"
  dataFrom:
  - extract:
      key: moosefs
