---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "csi-moosefs-config"
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        master_host: "{{ .MOOSEFS_MASTER_HOST }}"
        master_port: "{{ .MOOSEFS_MASTER_PORT }}"
        k8s_root_dir: "/"
        driver_working_dir: "pv_data"
        mount_count: "1"
        mfs_logging: "true"
  data:
    - secretKey: MOOSEFS_MASTER_HOST
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: df1f2680-74d5-44f2-9b81-b106016f4a9f
        property: mfshost
    - secretKey: MOOSEFS_MASTER_PORT
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: df1f2680-74d5-44f2-9b81-b106016f4a9f
        property: mfsport
