---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: guarded
        url: "https://${GATUS_SUBDOMAIN:-${APP}}.${GATUS_DOMAIN:-${SECRET_DOMAIN}}${GATUS_PATH:-/}"
        interval: 1m
        client:
          dns-resolver: ${SECRET_CLUSTER_RESOLVER}
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
        alerts:
          - type: discord
