---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        BUCKET_HOST: "{{ .BUCKET_HOST }}"
        BUCKET_NAME: "loki"
        BUCKET_REGION: ""
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: BUCKET_HOST
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3e78cdee-d25b-4eaa-acee-b10d012d4014
        property: BUCKET_HOST
    - secretKey: AWS_ACCESS_KEY_ID
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3e78cdee-d25b-4eaa-acee-b10d012d4014
        property: username
    - secretKey: AWS_SECRET_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 3e78cdee-d25b-4eaa-acee-b10d012d4014
        property: password
