---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name loki-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        BUCKET_HOST: "{{ .bucket_host }}"
        BUCKET_NAME: "loki"
        BUCKET_REGION: ""
        AWS_ACCESS_KEY_ID: "{{ .s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .s3_secret_key }}"
  dataFrom:
  - extract:
      key: loki
