---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kapowarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      kapowarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/tparker00/kapowarr
              tag: de9f73aff774a1c667298fa8e7fcebc448cc5d8d
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 15m
                memory: 350M
              limits:
                memory: 600M
    service:
      main:
        controller: *app
        primary: true
        ports:
          http:
            port: 5656
    ingress:
      main:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Kapowarr
          gethomepage.dev/icon: calibre-web.png
          gethomepage.dev/description: Comic Downloads
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/db
      data:
        enabled: true
        existingClaim: downloads-rw
        globalMounts:
          - path: /data
