---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    controller:
      resources:
        requests:
          cpu: 35m
          memory: 64M
        limits:
          cpu: null
          memory: 128M
    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: null
          memory: 64M
        limits:
          memory: 64M
      ingress:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
