apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_MFS_DATA: ENC[AES256_GCM,data:IId9SndYO/k=,iv:usbzdfEVmatcJrcosdasIuPVsKVZejRX0I2yAfhRzC8=,tag:kpsoi5w9WiBnXWs/bBSNog==,type:str]
    SECRET_MFS_MINIO: ENC[AES256_GCM,data:matjeWOtS23lZvO8l8c=,iv:bWruwv+UENYMnuJoeW88wi77fFyLKCMON9ZUhd/WRS8=,tag:Fb/N+Gipm2JfESkLlkDDpA==,type:str]
    SECRET_MFS_POSTGRES: ENC[AES256_GCM,data:PNvlBh6Dfj+2Motaz2JQ63HjDLBxT5CsUg==,iv:z3ypObfBBXtsXmPKgk45VdlUb7wuaiJXdwjQlmglgZ8=,tag:Hp/tf+e0RsBI08iviPsWBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVmo2dk1sOEI5emcrUHJs
            WEtkNE4xdkIvSEpGZG9GbjVBMEhkQ0QyL1NvCkpXMTRjVVEzWDZaWVFWWjh0bFRD
            UEkxZVJTTVFtUmx0eWdxRjNWUUhWY1UKLS0tIHJvZ0hzbUtnclZHOUZ1NElPdEE2
            RXhETDBPUnhGWE9kR1JBdURiV2xYYncKdbKWyXHu6NRJ/cTFHPAqOTChdknaZeuj
            lBwiNudAFsiZGFCVLxjfMcneQp6PXtDr5OjHqeFp0DlkTtQsVYHX4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-30T04:07:44Z"
    mac: ENC[AES256_GCM,data:3L3pWVYEr85SI2c9Akhj/PAXgud0oevaj6CusPaicnEleYaOfORYaLNrz8kVgf+ukcoTvUyLcUR/MaNkkCkEWSmVkOveZj7tR89eVLInHqzrhpvxu8XcBWSDjMTjrv4XwtYYxTdNM3t+mstu5JhLCjmmlmlsrG3l58E7V2Vaeb0=,iv:Pvqb1HGDoImOdh1qkoe2noyU9S4+RFi6nN1VnTmqdF4=,tag:ZdYyGiUSbSWG2s2oRqw1Kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
