apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EDSIoRKPqe6qNPc=,iv:3e2c3pBQcvuKrCe616Y+mhxAuYBSiPb/tIqSIkFpOVM=,tag:HluEI7OCmhMZeKgNyVbOHA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:SY7BZkUnERLHdhA9A706l+JkY/DqXg==,iv:nTyXbKsNFvvlrfW7BLU5jRfR9lJ2LYUsljONv8TH6SA=,tag:PIt6xjUGqv2nhAGCqJZTzg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:thVmPJFjk6w7hGz2qYgBr1UZgZ28nkjvw8hpaKYEzzcqIw80,iv:zL/gnfKnyYbx+5j7zEY7DiJGxh7yEtoE4DECt4JWloU=,tag:6v5RiaMnY4tYF04zNy6rpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT25JVkVvQzNscytkWmFi
            YjMvOGNrN0RUalB5UGVYYTFvMzlDcWprYkM4CnhnMlRrMGl4YmNNOTBqeGlqbzEw
            T0pZcjJ3OHBSaGNQMHhrSzY3aHdmS28KLS0tIEZXMDlNTVVXdlhzeWRvL3phSGQ5
            VlFUK0dFYVJLSExVVWlaR0ZKbWxSaWcKdM2QZAasGulo1tAuv9mc3b5QQbutcfVf
            LlNeNRlGqLPc06gdSwYVvYwq+Ye5Fmy007qayrr5YXtjqj9ix78HBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T15:03:41Z"
    mac: ENC[AES256_GCM,data:KWFAFhrtbRsEawdxdsP9jkvk/kd6Svyr63H12/dLIrnlALjrm38ULJ9PApQGJArmoHtjOFpsPiu0Q/Vx07/+KithHBwA1f6aUsyEXqi6zPz7aVdgOIckslfL6U8DPAhVmy+lyTCHzrBH/JH63hP4WJHobrFIJgvtxfdAXD8r8Ac=,iv:In/nboSiTVPQX8I/acKI0/pFeUCbix8MDbRJzSWqbXY=,tag:DjdYFQj5/4GkObg+fkRBYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
