---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  COREDNS_ADDR: "10.51.0.10"
  KUBE_API_ADDR: "10.10.5.5"
  CLUSTER_CIDR: "10.50.0.0/16"
  SERVICE_CIDR: "10.51.0.0/16"
  NODE_CIDR: "10.10.5.0/24"
