---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name pmm-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: pmm-config-tpl
            items:
              - key: config.yml
  dataFrom:
  - extract:
      key: plex
  - extract:
      key: tautulli
  - extract:
      key: tmdb
  - extract:
      key: omdb
  - extract:
      key: mdblist
  - extract:
      key: radarr
  - extract:
      key: sonarr
  - extract:
      key: trakt
