---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pmm-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      templateFrom:
        - configMap:
            name: pmm-config-tpl
            items:
              - key: config.yml
  data:
    - secretKey: PLEX_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 557de7c6-1ee4-4ef5-9eaa-b10900f5c0ff
        property: token
    - secretKey: TAUTULLI_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 9bd4b81b-8ca5-47c3-83c8-b10900f6266c
        property: k8s_token
    - secretKey: TMDB_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: efd16abb-bfc9-4963-9f53-b10901039253
        property: token
    - secretKey: OMDB_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3ae90e87-930f-43f7-b3cd-b1090103e99e
        property: token
    - secretKey: MDBLIST_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c57c1a3d-a594-45c0-aaab-b1090104b9b1
        property: token
    - secretKey: RADARR_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 5b82ac2c-9c1d-4afe-97e5-b10800445be1
        property: token
    - secretKey: SONARR_APIKEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 49e66475-bf8d-437b-9df0-b107000cb249
        property: token
    - secretKey: TRAKT_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 72324cb3-e830-404b-a0f8-b1090106d49a
        property: client_id
    - secretKey: TRAKT_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 72324cb3-e830-404b-a0f8-b1090106d49a
        property: client_secret
    - secretKey: TRAKT_ACCESS_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 72324cb3-e830-404b-a0f8-b1090106d49a
        property: access_token
    - secretKey: PIN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 72324cb3-e830-404b-a0f8-b1090106d49a
        property: ping

