apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - helmrelease.yaml
  - externalsecret.yaml
  - ../../../../templates/moosefs
configMapGenerator:
  - name: pgadmin-local-config-configmap
    files:
      - config_local.py
generatorOptions:
  disableNameSuffixHash: true
