---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${CLAIM:-${APP}}"
spec:
  accessModes: ["${MFS_ACCESSMODES:-ReadWriteOnce}"]
  resources:
    requests:
      storage: "${MFS_CAPACITY}"
  storageClassName: moosefs-storage
