---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        READARR__API_KEY: &apiKey "{{ .READARR__API_KEY }}"
        READARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        READARR__POSTGRES_PORT: "5432"
        READARR__POSTGRES_USER: &dbUser "{{ .READARR__POSTGRES_USER }}"
        READARR__POSTGRES_PASSWORD: &dbPass "{{ .READARR__POSTGRES_PASSWORD }}"
        READARR__POSTGRES_MAIN_DB: readarr_main
        READARR__POSTGRES_LOG_DB: readarr_log
        READARR__POSTGRES_CACHE_DB: readarr_cache
        # Postgres Init
        INIT_POSTGRES_DBNAME: readarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Exportar vars
        APIKEY: *apiKey
        URL: "{{ .READARR_URL }}"
  data:
    - secretKey: READARR__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0bd82a9e-01df-4638-9eb0-b12d015b6ca4
        property: token
    - secretKey: READARR__POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0bd82a9e-01df-4638-9eb0-b12d015b6ca4
        property: pg_user
    - secretKey: READARR__POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0bd82a9e-01df-4638-9eb0-b12d015b6ca4
        property: pg_password
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6c1e4615-5100-4dab-a169-b107003f2677
        property: password
    - secretKey: READARR_URL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0bd82a9e-01df-4638-9eb0-b12d015b6ca4
        property: readarr_url
