---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name readarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        READARR__API_KEY: &apiKey "{{ .readarr_token }}"
        READARR__POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        READARR__POSTGRES_PORT: "5432"
        READARR__POSTGRES_USER: &dbUser "{{ .pg_user }}"
        READARR__POSTGRES_PASSWORD: &dbPass "{{ .pg_pass }}"
        READARR__POSTGRES_MAIN_DB: readarr_main
        READARR__POSTGRES_LOG_DB: readarr_log
        READARR__POSTGRES_CACHE_DB: readarr_cache
        # Postgres Init
        INIT_POSTGRES_DBNAME: readarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
        # Exportar vars
        APIKEY: *apiKey
        URL: "{{ .url }}"
  dataFrom:
  - extract:
      key: readarr
  - extract:
      key: cloudnative-pg
