apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:cf83kzG6LPCDgt9uj9FyA7Dwji+EEauk7WbassCOlxPr99ub4DfbRQ==,iv:BfZ59oL+4pwKecoarOaRBXzcqkN6G+C6qgHxeHKV878=,tag:ckR7sXNPq4oRTcYpsS8YyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L1U5YXhvcFZKQU5waXpS
            SFYzUmsrcFNuUXBSdzBwVStvTjBEN2hsUTE0Ckw2OHR6T3BjbkdYSU9BT3lMcW5D
            SjhjeVpSNjB6VTBQQnNLckFlQlFlaUUKLS0tIDd5cHV5cWdBalQ4Zm9zb3p0cUx1
            RzVyUVpWL2trWWZ3eFlmdFZ2cTZIM0UKyKNRX/zExoyOt31894KxCyn+tCoVsXVu
            ufozA7P1uG0sDSfkQ2AP4bSkbXpp3Mn7TGsIedOasRGQcdBf6Xob8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-29T17:20:21Z"
    mac: ENC[AES256_GCM,data:SE/2qrbn01mtFxqJXgZs5KFe80blsacBiGVY5Mn5MOSdfG5Qh0IscdWaj6sli78hBx02QJDh+biyljbub85QG82c4Cin1MUjhpz78aglkpF8DKWx22mFi1yBuqsJAjds2i45GDFRdqUqdOPMQSa4U2UZo3VOokTEcBmy04dVmhA=,iv:dEJXWvPmH+nJ5h3ehbYdujAzafyV3L/hwAkk1fV1gQU=,tag:IBxkdxm2KxBAv5d8cwzQXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
