apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Lo7Ih15y6ladqEYmkL+64gDMQ38EVKWiXsUWaF2tQpl8jUpH2TAAYg==,iv:wg6h6QaKkcwq7cXAnuhQ69uMagovrm6ucpMic4LXCA4=,tag:LcubfMZjIbDBaNcFihrsiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1a1JNek9qQmtuZCtac1Ft
            aFlBbzhHSWIxWWQ1Tm5ibWZkYldDaHdRekNVCkpkOVVDUUxxQ2xhdWF1a25DVE9s
            TmZUZWU0dERqM2lFU3VPNkN6RXdKcVkKLS0tIFE3OEJSMEE5dUhlNVZlQ29xcU1C
            blErQmcyeXpzRFF4NUN0ZU11UWJTTEUKr8AGSW9fLK2zDNafuxnaNVdaqCxF0+P6
            Doo6v8qInHovjeeaatvcVBQgqiYoXkPkNZ+KZ8WKw9u6xVz9Fela/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-29T02:30:54Z"
    mac: ENC[AES256_GCM,data:mVoXIb1GTkoHMOKnpU+4q0xZE27POWv4NExeZp9CA/dXsrpkQzONTLJNyrPKAByCI/lWsuBXopTgE2jrF4ut29Isql749QQX3SXPHdDWmsmX2nKMs9wZsT/lOIZQMzRAx+Pr5WkGf5Xr0K0a05vTTd03UESkienbGPBz29mvfko=,iv:ktSPDAI3r7Bb1m//29c1Emuoci1pCunF58yzIPvypt4=,tag:qdYIMOvAknDToLOMiu5TbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
